kumuluzee:
  datasources:
  - jndi-name: jdbc/trackingms
    connection-url: jdbc:mysql://localhost:3306/trackingmsdb?zeroDateTimeBehavior=CONVERT_TO_NULL&serverTimezone=EST
    username: trackingmsdb
    password: trackingmsdb
    pool:
      max-size: 5
  amqp:
    rabbitmq:
      hosts:
      - name: CargoMQ
        url:  localhost
        username: guest
        password: guest
        exchanges:
        - name: cargoExchange
          type: direct