kumuluzee:
  datasources:
  - jndi-name: jdbc/bookingms
    connection-url: jdbc:mysql://localhost:3306/bookingmsdb?zeroDateTimeBehavior=CONVERT_TO_NULL&serverTimezone=EST
    username: bookingmsdb
    password: bookingmsdb
    pool:
      max-size: 5
  amqp:
    rabbitmq:
      hosts:
      - name: CargoMQ
        url:  localhost
        username: guest
        password: guest
        exchanges:
        - name: cargoExchange
          type: direct