kumuluzee:
  datasources:
  - jndi-name: jdbc/handlingms
    connection-url: jdbc:mysql://localhost:3306/handlingmsdb?zeroDateTimeBehavior=CONVERT_TO_NULL&serverTimezone=EST
    username: handlingmsdb
    password: handlingmsdb
    pool:
      max-size: 5
  amqp:
    rabbitmq:
      hosts:
      - name: CargoTrackerMQ
        url: localhost
        username: guest
        password: guest
        exchanges:
        - name: cargoExchange
          type: direct